### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by tking** [rtrlib/bird-rtrlib-cli#10]
Hi developers,

I get the following compile error: bin/bird-rtrlib-cli/rtr.c: In function ‘rtr_create_ssh_config’:
bin/bird-rtrlib-cli/rtr.c:36:51: error: invalid application of ‘sizeof’ to incomplete type ‘struct tr_ssh_config’
     struct tr_ssh_config *result = malloc(sizeof (struct tr_ssh_config));
                                                   ^
bin/bird-rtrlib-cli/rtr.c:37:31: error: invalid application of ‘sizeof’ to incomplete type ‘struct tr_ssh_config’
     memset(result, 0, sizeof (struct tr_ssh_config));
                               ^
bin/bird-rtrlib-cli/rtr.c:40:15: error: dereferencing pointer to incomplete type ‘struct tr_ssh_config’
         result->host = strdup(host);

Could you please fix this?

Best regards,
Thomas

**Comment by waehlisch** [comment]
@tking which RTRlib verison do you use? Latest master branch or one of the official releases?

**Comment by tking** [comment]
Latest master branch.Best regards,ThomasOn Jan 3, 2017 23:41, Matthias Wählisch <notifications@github.com> wrote:@tking which RTRlib verison do you use? Latest master branch or one of the official releases?

**Comment by fho** [comment]
I was able to reproduce the problem.
If rtrlib was compiled without libssh support and bird-rtrlib-cli is being compiled with libssh installed that error occurs.
That is a bug the Cmake script of bird-rtrlib-cli should check if libssh is installed AND if rtrlib is compiled with SSH support.

Can you please try to recompile and reinstall rtrlib and then recompile bird-rtrlib-cli again?
When you call "cmake ." in the rtrlib directory the message:

> -- libssh found, building librtr with SSH 0.6.0 support


should be printed

**Comment by tking** [comment]
I can confirm that it now compiles and works. Thanks for your support!
