### ISSUE TITLE
Can not be compiled FreeBSD

### ISSUE THREAD

**Issue by netfreak98** [rtrlib/bird-rtrlib-cli#14]
When I tried to compile it on FreeBSD 11.2, I got the following error:

root@ffm01:/root/bird-rtrlib-cli # make
Scanning dependencies of target bird-rtrlib-cli
[ 16%] Building C object CMakeFiles/bird-rtrlib-cli.dir/bird-rtrlib-cli.c.o
/root/bird-rtrlib-cli/bird-rtrlib-cli.c:393:13: warning: implicit declaration of function 'getline' is invalid in C99 [-Wimplicit-function-declaration]
            while (getline(&command, &command_len, stdin) != -1) {
                   ^
1 warning generated.
[ 33%] Building C object CMakeFiles/bird-rtrlib-cli.dir/bird.c.o
[ 50%] Building C object CMakeFiles/bird-rtrlib-cli.dir/rtr.c.o
[ 66%] Building C object CMakeFiles/bird-rtrlib-cli.dir/cli.c.o
[ 83%] Building C object CMakeFiles/bird-rtrlib-cli.dir/config.c.o
[100%] Linking C executable bird-rtrlib-cli
CMakeFiles/bird-rtrlib-cli.dir/cli.c.o: In function `parse_cli':
cli.c:(.text+0x75): undefined reference to `argp_parse'
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Stop.
make[2]: stopped in /root/bird-rtrlib-cli
*** Error code 1

Stop.
make[1]: stopped in /root/bird-rtrlib-cli
*** Error code 1

Stop.
make: stopped in /root/bird-rtrlib-cli

**Comment by mroethke** [comment]
Can you try #15?

**Comment by smlng** [comment]
#15 is in, please confirm it helps (and close this then)

**Comment by smlng** [comment]
ping

**Comment by netfreak98** [comment]
Hi, I'm sorry.. found your last message from github in my spam folder. Now everything is working, thanks :)

**Comment by netfreak98** [comment]
``root@test:~/bird-rtrlib-cli # cmake .
-- argp found.
-- Found RTR: /usr/local/lib/librtr.so  
-- rtrlib found.
-- Configuring done
-- Generating done
-- Build files have been written to: /root/bird-rtrlib-cli
root@test:~/bird-rtrlib-cli # make
Scanning dependencies of target bird-rtrlib-cli
[ 16%] Building C object CMakeFiles/bird-rtrlib-cli.dir/bird-rtrlib-cli.c.o
/root/bird-rtrlib-cli/bird-rtrlib-cli.c:393:13: warning: implicit declaration of
      function 'getline' is invalid in C99 [-Wimplicit-function-declaration]
            while (getline(&command, &command_len, stdin) != -1) {
                   ^
1 warning generated.
[ 33%] Building C object CMakeFiles/bird-rtrlib-cli.dir/bird.c.o
[ 50%] Building C object CMakeFiles/bird-rtrlib-cli.dir/rtr.c.o
[ 66%] Building C object CMakeFiles/bird-rtrlib-cli.dir/cli.c.o
[ 83%] Building C object CMakeFiles/bird-rtrlib-cli.dir/config.c.o
[100%] Linking C executable bird-rtrlib-cli
[100%] Built target bird-rtrlib-cli
root@test:~/bird-rtrlib-cli #

**Comment by smlng** [comment]
thanks for reporting, closing.
